name: agri
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  hooks_riverpod: ^2.6.1
  iconsax_plus: ^1.0.0
  image_picker: ^1.2.1
  injectable: ^2.7.1+4
  intl: ^0.20.2
  lazy_load_indexed_stack: ^1.2.1
  mime: ^2.0.0
  objectbox: ^5.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  qr_code_scanner:
    git:
      url: https://github.com/huypanha/qr_code_scanner/
  qr_flutter: ^4.1.0
  socket_io_client: ^3.1.4
  url_launcher: ^6.3.2
  objectbox_sync_flutter_libs: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.7
  pinput: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.5
  injectable_generator: ^2.12.0
  objectbox_generator: any
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true # Add this line here
  fonts:
  - family:  MyFlutterApp
    fonts:
      - asset: assets/fonts/MyFlutterApp.ttf
  assets:
    - assets/
    - assets/images/
    - assets/SVG/
    - assets/png/

objectbox:
  output_dir: data/data_sources

flutter_native_splash:
  android: true
  ios: false
  web: false
  color: "#ffffff" # Background color
  image: assets\png\app_splash.png # Your splash image path
  android_gravity: center
  # Configeration for The Splash screen for Android 12+
  android_12:
    image: assets\png\app_splash.png # Background image for Android 12
    color: "#ffffff" # Background color for Android 12
    # icon_background_color: "#0082FE" # Icon background color
    # android_gravity: fill # Stretch the image to fill the screen
    # android_gravity: fill #  Stretch the image to fill the screen
  # Command Line to set native splash
  # dart run flutter_native_splash:create
  # color & background_image attribute
  #   - color : to select splash background color
  #   - background_image : to select splash background image
  #   - choose between it or background_image

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/png/app_icon.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21
