// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import '../../data/models/locale.dart';
import '../../data/models/user.dart';
import '../../modules/auth/data/models/auth_token.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8191001011009218982),
    name: 'AuthToken',
    lastPropertyId: const obx_int.IdUid(3, 4125816811933832349),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2228108815030582429),
        name: 'storageID',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 742092984816188115),
        name: 'token',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4125816811933832349),
        name: 'refreshToken',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1079510562737757718),
    name: 'LocaleModel',
    lastPropertyId: const obx_int.IdUid(3, 5783494486336196983),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2683728821773813527),
        name: 'storageID',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 517588696485665186),
        name: 'languageCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5783494486336196983),
        name: 'isFirstTime',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 3379791530785140218),
    name: 'User',
    lastPropertyId: const obx_int.IdUid(30, 3198876252525019743),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6285474902773064722),
        name: 'storageID',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2742488988015312469),
        name: 'userID',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 6555721987836142718),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1122004979063295114),
        name: 'firstName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5540807986218267836),
        name: 'lastName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7488471668424326960),
        name: 'fullNameOnId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4618964508325505055),
        name: 'nationalId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7680832610000945002),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4114172744283726683),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8905163284052482006),
        name: 'birthDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 1135089138908269607),
        name: 'gender',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6812454584161526051),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 375987656918990642),
        name: 'emailVerifiedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7712800612879847154),
        name: 'phoneVerifiedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3389882637997125613),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4282167945620272520),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 1271201779807569767),
        name: 'acceptedTerms',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8150502816201078488),
        name: 'acceptedTermsAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 6407386176097255300),
        name: 'acceptedDisclaimer',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 3302614490899144755),
        name: 'acceptedDisclaimerAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 4287427099188539931),
        name: 'patientDetailsComplete',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 3867094119670243555),
        name: 'patientDetailsCompletedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 4457132370580481998),
        name: 'providerDetailsComplete',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 4561610130269683014),
        name: 'providerDetailsCompletedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 8605421849836641241),
        name: 'categoryId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 5976176258920198041),
        name: 'requestUpdatedBy',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 3380747400242707519),
        name: 'requestUpdatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 927808250892560947),
        name: 'declinationReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 2957840177645514620),
        name: 'onlineStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 3563285707346189738),
        name: 'avatar',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 3198876252525019743),
        name: 'isProvider',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 3379791530785140218),
    lastIndexId: const obx_int.IdUid(1, 6555721987836142718),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AuthToken: obx_int.EntityDefinition<AuthToken>(
      model: _entities[0],
      toOneRelations: (AuthToken object) => [],
      toManyRelations: (AuthToken object) => {},
      getId: (AuthToken object) => object.storageID,
      setId: (AuthToken object, int id) {
        object.storageID = id;
      },
      objectToFB: (AuthToken object, fb.Builder fbb) {
        final tokenOffset = fbb.writeString(object.token);
        final refreshTokenOffset = object.refreshToken == null
            ? null
            : fbb.writeString(object.refreshToken!);
        fbb.startTable(4);
        fbb.addInt64(0, object.storageID);
        fbb.addOffset(1, tokenOffset);
        fbb.addOffset(2, refreshTokenOffset);
        fbb.finish(fbb.endTable());
        return object.storageID;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final tokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final refreshTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object =
            AuthToken(token: tokenParam, refreshToken: refreshTokenParam)
              ..storageID = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                4,
                0,
              );

        return object;
      },
    ),
    LocaleModel: obx_int.EntityDefinition<LocaleModel>(
      model: _entities[1],
      toOneRelations: (LocaleModel object) => [],
      toManyRelations: (LocaleModel object) => {},
      getId: (LocaleModel object) => object.storageID,
      setId: (LocaleModel object, int id) {
        object.storageID = id;
      },
      objectToFB: (LocaleModel object, fb.Builder fbb) {
        final languageCodeOffset = fbb.writeString(object.languageCode);
        fbb.startTable(4);
        fbb.addInt64(0, object.storageID);
        fbb.addOffset(1, languageCodeOffset);
        fbb.addBool(2, object.isFirstTime);
        fbb.finish(fbb.endTable());
        return object.storageID;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final languageCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final isFirstTimeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final object =
            LocaleModel(
                languageCode: languageCodeParam,
                isFirstTime: isFirstTimeParam,
              )
              ..storageID = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                4,
                0,
              );

        return object;
      },
    ),
    User: obx_int.EntityDefinition<User>(
      model: _entities[2],
      toOneRelations: (User object) => [],
      toManyRelations: (User object) => {},
      getId: (User object) => object.storageID,
      setId: (User object, int id) {
        object.storageID = id;
      },
      objectToFB: (User object, fb.Builder fbb) {
        final userIDOffset = fbb.writeString(object.userID);
        final firstNameOffset = object.firstName == null
            ? null
            : fbb.writeString(object.firstName!);
        final lastNameOffset = object.lastName == null
            ? null
            : fbb.writeString(object.lastName!);
        final fullNameOnIdOffset = object.fullNameOnId == null
            ? null
            : fbb.writeString(object.fullNameOnId!);
        final nationalIdOffset = object.nationalId == null
            ? null
            : fbb.writeString(object.nationalId!);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final genderOffset = object.gender == null
            ? null
            : fbb.writeString(object.gender!);
        final requestUpdatedByOffset = object.requestUpdatedBy == null
            ? null
            : fbb.writeString(object.requestUpdatedBy!);
        final declinationReasonOffset = object.declinationReason == null
            ? null
            : fbb.writeString(object.declinationReason!);
        final onlineStatusOffset = object.onlineStatus == null
            ? null
            : fbb.writeString(object.onlineStatus!);
        final avatarOffset = object.avatar == null
            ? null
            : fbb.writeString(object.avatar!);
        fbb.startTable(31);
        fbb.addInt64(0, object.storageID);
        fbb.addOffset(1, userIDOffset);
        fbb.addOffset(2, firstNameOffset);
        fbb.addOffset(3, lastNameOffset);
        fbb.addOffset(4, fullNameOnIdOffset);
        fbb.addOffset(5, nationalIdOffset);
        fbb.addOffset(6, emailOffset);
        fbb.addOffset(7, phoneOffset);
        fbb.addInt64(8, object.birthDate?.millisecondsSinceEpoch);
        fbb.addOffset(9, genderOffset);
        fbb.addBool(10, object.isActive);
        fbb.addInt64(11, object.emailVerifiedAt?.millisecondsSinceEpoch);
        fbb.addInt64(12, object.phoneVerifiedAt?.millisecondsSinceEpoch);
        fbb.addInt64(13, object.createdAt?.millisecondsSinceEpoch);
        fbb.addInt64(14, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addBool(15, object.acceptedTerms);
        fbb.addInt64(16, object.acceptedTermsAt?.millisecondsSinceEpoch);
        fbb.addBool(17, object.acceptedDisclaimer);
        fbb.addInt64(18, object.acceptedDisclaimerAt?.millisecondsSinceEpoch);
        fbb.addBool(19, object.patientDetailsComplete);
        fbb.addInt64(
          20,
          object.patientDetailsCompletedAt?.millisecondsSinceEpoch,
        );
        fbb.addBool(21, object.providerDetailsComplete);
        fbb.addInt64(
          22,
          object.providerDetailsCompletedAt?.millisecondsSinceEpoch,
        );
        fbb.addInt64(23, object.categoryId);
        fbb.addOffset(24, requestUpdatedByOffset);
        fbb.addInt64(25, object.requestUpdatedAt?.millisecondsSinceEpoch);
        fbb.addOffset(26, declinationReasonOffset);
        fbb.addOffset(27, onlineStatusOffset);
        fbb.addOffset(28, avatarOffset);
        fbb.addBool(29, object.isProvider);
        fbb.finish(fbb.endTable());
        return object.storageID;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final birthDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final emailVerifiedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final phoneVerifiedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          32,
        );
        final acceptedTermsAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          36,
        );
        final acceptedDisclaimerAtValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 40);
        final patientDetailsCompletedAtValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 44);
        final providerDetailsCompletedAtValue = const fb.Int64Reader()
            .vTableGetNullable(buffer, rootOffset, 48);
        final requestUpdatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          54,
        );
        final userIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final isProviderParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          62,
          false,
        );
        final firstNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final lastNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final fullNameOnIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final nationalIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final birthDateParam = birthDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(birthDateValue);
        final genderParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final isActiveParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final emailVerifiedAtParam = emailVerifiedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(emailVerifiedAtValue);
        final phoneVerifiedAtParam = phoneVerifiedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(phoneVerifiedAtValue);
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final acceptedTermsParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          34,
        );
        final acceptedTermsAtParam = acceptedTermsAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(acceptedTermsAtValue);
        final acceptedDisclaimerParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          38,
        );
        final acceptedDisclaimerAtParam = acceptedDisclaimerAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(acceptedDisclaimerAtValue);
        final patientDetailsCompleteParam = const fb.BoolReader()
            .vTableGetNullable(buffer, rootOffset, 42);
        final patientDetailsCompletedAtParam =
            patientDetailsCompletedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(
                patientDetailsCompletedAtValue,
              );
        final providerDetailsCompleteParam = const fb.BoolReader()
            .vTableGetNullable(buffer, rootOffset, 46);
        final providerDetailsCompletedAtParam =
            providerDetailsCompletedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(
                providerDetailsCompletedAtValue,
              );
        final requestUpdatedByParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 52);
        final requestUpdatedAtParam = requestUpdatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(requestUpdatedAtValue);
        final declinationReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 56);
        final onlineStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 58);
        final avatarParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 60);
        final categoryIdParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          50,
        );
        final object =
            User(
                userID: userIDParam,
                isProvider: isProviderParam,
                firstName: firstNameParam,
                lastName: lastNameParam,
                fullNameOnId: fullNameOnIdParam,
                nationalId: nationalIdParam,
                email: emailParam,
                phone: phoneParam,
                birthDate: birthDateParam,
                gender: genderParam,
                isActive: isActiveParam,
                emailVerifiedAt: emailVerifiedAtParam,
                phoneVerifiedAt: phoneVerifiedAtParam,
                createdAt: createdAtParam,
                updatedAt: updatedAtParam,
                acceptedTerms: acceptedTermsParam,
                acceptedTermsAt: acceptedTermsAtParam,
                acceptedDisclaimer: acceptedDisclaimerParam,
                acceptedDisclaimerAt: acceptedDisclaimerAtParam,
                patientDetailsComplete: patientDetailsCompleteParam,
                patientDetailsCompletedAt: patientDetailsCompletedAtParam,
                providerDetailsComplete: providerDetailsCompleteParam,
                providerDetailsCompletedAt: providerDetailsCompletedAtParam,
                requestUpdatedBy: requestUpdatedByParam,
                requestUpdatedAt: requestUpdatedAtParam,
                declinationReason: declinationReasonParam,
                onlineStatus: onlineStatusParam,
                avatar: avatarParam,
                categoryId: categoryIdParam,
              )
              ..storageID = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                4,
                0,
              );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AuthToken] entity fields to define ObjectBox queries.
class AuthToken_ {
  /// See [AuthToken.storageID].
  static final storageID = obx.QueryIntegerProperty<AuthToken>(
    _entities[0].properties[0],
  );

  /// See [AuthToken.token].
  static final token = obx.QueryStringProperty<AuthToken>(
    _entities[0].properties[1],
  );

  /// See [AuthToken.refreshToken].
  static final refreshToken = obx.QueryStringProperty<AuthToken>(
    _entities[0].properties[2],
  );
}

/// [LocaleModel] entity fields to define ObjectBox queries.
class LocaleModel_ {
  /// See [LocaleModel.storageID].
  static final storageID = obx.QueryIntegerProperty<LocaleModel>(
    _entities[1].properties[0],
  );

  /// See [LocaleModel.languageCode].
  static final languageCode = obx.QueryStringProperty<LocaleModel>(
    _entities[1].properties[1],
  );

  /// See [LocaleModel.isFirstTime].
  static final isFirstTime = obx.QueryBooleanProperty<LocaleModel>(
    _entities[1].properties[2],
  );
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.storageID].
  static final storageID = obx.QueryIntegerProperty<User>(
    _entities[2].properties[0],
  );

  /// See [User.userID].
  static final userID = obx.QueryStringProperty<User>(
    _entities[2].properties[1],
  );

  /// See [User.firstName].
  static final firstName = obx.QueryStringProperty<User>(
    _entities[2].properties[2],
  );

  /// See [User.lastName].
  static final lastName = obx.QueryStringProperty<User>(
    _entities[2].properties[3],
  );

  /// See [User.fullNameOnId].
  static final fullNameOnId = obx.QueryStringProperty<User>(
    _entities[2].properties[4],
  );

  /// See [User.nationalId].
  static final nationalId = obx.QueryStringProperty<User>(
    _entities[2].properties[5],
  );

  /// See [User.email].
  static final email = obx.QueryStringProperty<User>(
    _entities[2].properties[6],
  );

  /// See [User.phone].
  static final phone = obx.QueryStringProperty<User>(
    _entities[2].properties[7],
  );

  /// See [User.birthDate].
  static final birthDate = obx.QueryDateProperty<User>(
    _entities[2].properties[8],
  );

  /// See [User.gender].
  static final gender = obx.QueryStringProperty<User>(
    _entities[2].properties[9],
  );

  /// See [User.isActive].
  static final isActive = obx.QueryBooleanProperty<User>(
    _entities[2].properties[10],
  );

  /// See [User.emailVerifiedAt].
  static final emailVerifiedAt = obx.QueryDateProperty<User>(
    _entities[2].properties[11],
  );

  /// See [User.phoneVerifiedAt].
  static final phoneVerifiedAt = obx.QueryDateProperty<User>(
    _entities[2].properties[12],
  );

  /// See [User.createdAt].
  static final createdAt = obx.QueryDateProperty<User>(
    _entities[2].properties[13],
  );

  /// See [User.updatedAt].
  static final updatedAt = obx.QueryDateProperty<User>(
    _entities[2].properties[14],
  );

  /// See [User.acceptedTerms].
  static final acceptedTerms = obx.QueryBooleanProperty<User>(
    _entities[2].properties[15],
  );

  /// See [User.acceptedTermsAt].
  static final acceptedTermsAt = obx.QueryDateProperty<User>(
    _entities[2].properties[16],
  );

  /// See [User.acceptedDisclaimer].
  static final acceptedDisclaimer = obx.QueryBooleanProperty<User>(
    _entities[2].properties[17],
  );

  /// See [User.acceptedDisclaimerAt].
  static final acceptedDisclaimerAt = obx.QueryDateProperty<User>(
    _entities[2].properties[18],
  );

  /// See [User.patientDetailsComplete].
  static final patientDetailsComplete = obx.QueryBooleanProperty<User>(
    _entities[2].properties[19],
  );

  /// See [User.patientDetailsCompletedAt].
  static final patientDetailsCompletedAt = obx.QueryDateProperty<User>(
    _entities[2].properties[20],
  );

  /// See [User.providerDetailsComplete].
  static final providerDetailsComplete = obx.QueryBooleanProperty<User>(
    _entities[2].properties[21],
  );

  /// See [User.providerDetailsCompletedAt].
  static final providerDetailsCompletedAt = obx.QueryDateProperty<User>(
    _entities[2].properties[22],
  );

  /// See [User.categoryId].
  static final categoryId = obx.QueryIntegerProperty<User>(
    _entities[2].properties[23],
  );

  /// See [User.requestUpdatedBy].
  static final requestUpdatedBy = obx.QueryStringProperty<User>(
    _entities[2].properties[24],
  );

  /// See [User.requestUpdatedAt].
  static final requestUpdatedAt = obx.QueryDateProperty<User>(
    _entities[2].properties[25],
  );

  /// See [User.declinationReason].
  static final declinationReason = obx.QueryStringProperty<User>(
    _entities[2].properties[26],
  );

  /// See [User.onlineStatus].
  static final onlineStatus = obx.QueryStringProperty<User>(
    _entities[2].properties[27],
  );

  /// See [User.avatar].
  static final avatar = obx.QueryStringProperty<User>(
    _entities[2].properties[28],
  );

  /// See [User.isProvider].
  static final isProvider = obx.QueryBooleanProperty<User>(
    _entities[2].properties[29],
  );
}
