// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_sync_flutter_libs/objectbox_sync_flutter_libs.dart';

import '../../data/models/locale.dart';
import '../../data/models/user.dart';
import '../../modules/auth/data/models/auth_token.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8191001011009218982),
    name: 'AuthToken',
    lastPropertyId: const obx_int.IdUid(3, 4125816811933832349),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2228108815030582429),
        name: 'storageID',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 742092984816188115),
        name: 'token',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4125816811933832349),
        name: 'refreshToken',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 1079510562737757718),
    name: 'LocaleModel',
    lastPropertyId: const obx_int.IdUid(3, 5783494486336196983),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2683728821773813527),
        name: 'storageID',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 517588696485665186),
        name: 'languageCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5783494486336196983),
        name: 'isFirstTime',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 3379791530785140218),
    name: 'User',
    lastPropertyId: const obx_int.IdUid(34, 5697433829412434038),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6285474902773064722),
        name: 'storageID',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2742488988015312469),
        name: 'userID',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 6555721987836142718),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7680832610000945002),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4114172744283726683),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3389882637997125613),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 7602151119559130180),
        name: 'fullName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 2830976899945364076),
        name: 'isVerified',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 8601838952482382557),
        name: 'termsVersion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 5697433829412434038),
        name: 'termsAcceptedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 3379791530785140218),
    lastIndexId: const obx_int.IdUid(1, 6555721987836142718),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      1122004979063295114,
      5540807986218267836,
      7488471668424326960,
      4618964508325505055,
      8905163284052482006,
      1135089138908269607,
      6812454584161526051,
      375987656918990642,
      7712800612879847154,
      4282167945620272520,
      1271201779807569767,
      8150502816201078488,
      6407386176097255300,
      3302614490899144755,
      4287427099188539931,
      3867094119670243555,
      4457132370580481998,
      4561610130269683014,
      8605421849836641241,
      5976176258920198041,
      3380747400242707519,
      927808250892560947,
      2957840177645514620,
      3563285707346189738,
      3198876252525019743,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    AuthToken: obx_int.EntityDefinition<AuthToken>(
      model: _entities[0],
      toOneRelations: (AuthToken object) => [],
      toManyRelations: (AuthToken object) => {},
      getId: (AuthToken object) => object.storageID,
      setId: (AuthToken object, int id) {
        object.storageID = id;
      },
      objectToFB: (AuthToken object, fb.Builder fbb) {
        final tokenOffset = fbb.writeString(object.token);
        final refreshTokenOffset = object.refreshToken == null
            ? null
            : fbb.writeString(object.refreshToken!);
        fbb.startTable(4);
        fbb.addInt64(0, object.storageID);
        fbb.addOffset(1, tokenOffset);
        fbb.addOffset(2, refreshTokenOffset);
        fbb.finish(fbb.endTable());
        return object.storageID;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final tokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final refreshTokenParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object =
            AuthToken(token: tokenParam, refreshToken: refreshTokenParam)
              ..storageID = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                4,
                0,
              );

        return object;
      },
    ),
    LocaleModel: obx_int.EntityDefinition<LocaleModel>(
      model: _entities[1],
      toOneRelations: (LocaleModel object) => [],
      toManyRelations: (LocaleModel object) => {},
      getId: (LocaleModel object) => object.storageID,
      setId: (LocaleModel object, int id) {
        object.storageID = id;
      },
      objectToFB: (LocaleModel object, fb.Builder fbb) {
        final languageCodeOffset = fbb.writeString(object.languageCode);
        fbb.startTable(4);
        fbb.addInt64(0, object.storageID);
        fbb.addOffset(1, languageCodeOffset);
        fbb.addBool(2, object.isFirstTime);
        fbb.finish(fbb.endTable());
        return object.storageID;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final languageCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final isFirstTimeParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final object =
            LocaleModel(
                languageCode: languageCodeParam,
                isFirstTime: isFirstTimeParam,
              )
              ..storageID = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                4,
                0,
              );

        return object;
      },
    ),
    User: obx_int.EntityDefinition<User>(
      model: _entities[2],
      toOneRelations: (User object) => [],
      toManyRelations: (User object) => {},
      getId: (User object) => object.storageID,
      setId: (User object, int id) {
        object.storageID = id;
      },
      objectToFB: (User object, fb.Builder fbb) {
        final userIDOffset = fbb.writeString(object.userID);
        final emailOffset = object.email == null
            ? null
            : fbb.writeString(object.email!);
        final phoneOffset = object.phone == null
            ? null
            : fbb.writeString(object.phone!);
        final fullNameOffset = object.fullName == null
            ? null
            : fbb.writeString(object.fullName!);
        final termsVersionOffset = object.termsVersion == null
            ? null
            : fbb.writeString(object.termsVersion!);
        fbb.startTable(35);
        fbb.addInt64(0, object.storageID);
        fbb.addOffset(1, userIDOffset);
        fbb.addOffset(6, emailOffset);
        fbb.addOffset(7, phoneOffset);
        fbb.addInt64(13, object.createdAt?.millisecondsSinceEpoch);
        fbb.addOffset(30, fullNameOffset);
        fbb.addBool(31, object.isVerified);
        fbb.addOffset(32, termsVersionOffset);
        fbb.addInt64(33, object.termsAcceptedAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.storageID;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final createdAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final termsAcceptedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          70,
        );
        final userIDParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final fullNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 64);
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final isVerifiedParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          66,
        );
        final termsVersionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 68);
        final createdAtParam = createdAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
        final termsAcceptedAtParam = termsAcceptedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(termsAcceptedAtValue);
        final object =
            User(
                userID: userIDParam,
                fullName: fullNameParam,
                email: emailParam,
                phone: phoneParam,
                isVerified: isVerifiedParam,
                termsVersion: termsVersionParam,
                createdAt: createdAtParam,
                termsAcceptedAt: termsAcceptedAtParam,
              )
              ..storageID = const fb.Int64Reader().vTableGet(
                buffer,
                rootOffset,
                4,
                0,
              );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [AuthToken] entity fields to define ObjectBox queries.
class AuthToken_ {
  /// See [AuthToken.storageID].
  static final storageID = obx.QueryIntegerProperty<AuthToken>(
    _entities[0].properties[0],
  );

  /// See [AuthToken.token].
  static final token = obx.QueryStringProperty<AuthToken>(
    _entities[0].properties[1],
  );

  /// See [AuthToken.refreshToken].
  static final refreshToken = obx.QueryStringProperty<AuthToken>(
    _entities[0].properties[2],
  );
}

/// [LocaleModel] entity fields to define ObjectBox queries.
class LocaleModel_ {
  /// See [LocaleModel.storageID].
  static final storageID = obx.QueryIntegerProperty<LocaleModel>(
    _entities[1].properties[0],
  );

  /// See [LocaleModel.languageCode].
  static final languageCode = obx.QueryStringProperty<LocaleModel>(
    _entities[1].properties[1],
  );

  /// See [LocaleModel.isFirstTime].
  static final isFirstTime = obx.QueryBooleanProperty<LocaleModel>(
    _entities[1].properties[2],
  );
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// See [User.storageID].
  static final storageID = obx.QueryIntegerProperty<User>(
    _entities[2].properties[0],
  );

  /// See [User.userID].
  static final userID = obx.QueryStringProperty<User>(
    _entities[2].properties[1],
  );

  /// See [User.email].
  static final email = obx.QueryStringProperty<User>(
    _entities[2].properties[2],
  );

  /// See [User.phone].
  static final phone = obx.QueryStringProperty<User>(
    _entities[2].properties[3],
  );

  /// See [User.createdAt].
  static final createdAt = obx.QueryDateProperty<User>(
    _entities[2].properties[4],
  );

  /// See [User.fullName].
  static final fullName = obx.QueryStringProperty<User>(
    _entities[2].properties[5],
  );

  /// See [User.isVerified].
  static final isVerified = obx.QueryBooleanProperty<User>(
    _entities[2].properties[6],
  );

  /// See [User.termsVersion].
  static final termsVersion = obx.QueryStringProperty<User>(
    _entities[2].properties[7],
  );

  /// See [User.termsAcceptedAt].
  static final termsAcceptedAt = obx.QueryDateProperty<User>(
    _entities[2].properties[8],
  );
}
